version: "3"
services:
    www:
        build: .
        ports:
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
            - ./apache:/etc/apache2/sites-enabled/
        depends_on:
            - db
        networks:
             - default

    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./initSql:/docker-entrypoint-initdb.d/
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            default:
                aliases:
                    - hostName

    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 5050:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - default

    composer:
        image: composer   
        volumes:
#            - ./entrypoints:/usr/local/bin
            - ./www:/app
        command: install
#        command: "ln -s /usr/bin/php71 /usr/local/bin/php"
#        entrypoint: "/usr/local/bin/entrypointComposer.sh"
        networks:
            - default
        depends_on:
            - www
