version: "3"
services:
    www:
        build: .
        ports:
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - db
        networks:
             - default
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
#POSTGRES_USER: user
#POSTGRES_PASSWORD: test
#POSTGRES_DB: pgdb
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - default
